from flask import Flask, request, jsonify
import json

app=Flask(__name__)


residual={'input': 'give the total Acreage Burned by Region and Ownership in years 2018 and also provide disaster management strategies',
 'output': "In 2018, the total wildfire acreage burned was 8.8 million acres. Of this, 4.6 million acres (52%) burned on federal lands, with 2.3 million acres each on Forest Service and Department of Interior lands. The remaining 4.1 million acres (47%) burned on nonfederal lands.\n\nSome key disaster management strategies for wildfires include:\n\n1. Building community resilience through training, partnerships and capacity building \n2. Reducing vulnerabilities of at-risk communities through microfinance, retrofitting buildings, and stockpiling reconstruction materials\n3. Strengthening local governance through Disaster Management Authorities at all levels\n4. Institutionalizing national disaster management systems and capacities \n5. Taking a long-term, people-centered approach focused on local strengths and aspirations\n6. Ensuring political will, multi-stakeholder commitment and good governance to enable resilient communities\n\nA proactive approach centered on people's capacities and fostering an enabling environment is crucial for effective wildfire disaster management. The focus should be on strengthening resilience, not just reacting to vulnerabilities.",
 'intermediate_steps': '''[(AgentAction(tool='Wildfire Statistics', tool_input='What was the total acreage burned by region and ownership in 2018?', log='Here is my attempt at answering the question using the specified tools and format:\n\nQuestion: Give the total Acreage Burned by Region and Ownership in years 2018 and also provide disaster management strategies\n\nThought: To answer this, I will first use the Wildfire Statistics tool to get the acreage burned data for 2018. Then I will use the DISASTER MANAGEMENT STRATEGIES tool to provide relevant strategies.\n\nAction: Wildfire Statistics\nAction Input: What was the total acreage burned by region and ownership in 2018?'),
   'According to the data provided in Table 1 on page 1, in 2018 the total acreage burned was 8.8 million acres. Of this total, 4.6 million acres (52%) were on federal lands and 4.1 million acres (47%) were on nonfederal lands.\n\nThe federal acreage burned was split between:\n- Forest Service (FS): 2.3 million acres \n- Department of Interior (DOI): 2.3 million acres\n- Other federal agencies: less than 0.1 million acres\n\nSo in summary, for 2018 the acreage burned by region and ownership was:\n- Federal: 4.6 million acres total\n    - FS: 2.3 million acres\n    - DOI: 2.3 million acres \n    - Other federal: <0.1 million acres\n- Nonfederal: 4.1 million acres\n- Total: 8.8 million acres'),
  (AgentAction(tool='DISASTER MANAGEMENT STRATEGIES', tool_input='What are some key strategies for managing wildfires and reducing their impacts?', log='Now that I have the wildfire acreage data, I will use the DISASTER MANAGEMENT STRATEGIES tool to provide some relevant strategies for managing wildfires.\n\nAction: DISASTER MANAGEMENT STRATEGIES\nAction Input: What are some key strategies for managing wildfires and reducing their impacts?'),
   "Based on the provided context, some key strategies for managing wildfires and reducing their impacts include:\n\n1. Building community resilience through training programs, capacity building, and fostering public-private-people partnerships. This involves training construction engineers and masons on building disaster-resistant structures.\n\n2. Reducing vulnerabilities of communities at risk through microfinance support for affected small-scale enterprises, retrofitting public buildings, and supporting materials stockpiling for reconstruction. \n\n3. Strengthening governance mechanisms at the local level by constituting Disaster Management Authorities at national, state and district levels. This enables better coordination.\n\n4. Institutionalizing national systems and capacities for disaster management. The government should incorporate disaster mitigation into development projects and planning.\n\n5. Adopting a long-term perspective, fostering development of local capacity, and ensuring accountability to stakeholders in disaster management efforts.\n\n6. Focusing on people's strengths and aspirations, not just vulnerabilities, to boost resilience of local livelihoods in the face of risks. People-centered approaches can improve humanitarian aid and risk management.\n\nThe key is having strong political will, commitment from all actors, and good governance to create an environment that enables more resilient communities to thrive. A proactive approach centered on people's capacities is needed.")]'''}


@app.route("/response")

def response():
    output="Hello World"
    key_string=['output','intermediate_steps']
    
    print(jsonify({"output": residual['output'] , "intermediate": residual['intermediate_steps'] }))

    return jsonify({"output": residual['output'] , "intermediate": residual['intermediate_steps'] })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)